### PR TITLE
Fix Publishing

### PR DESCRIPTION
**Pull request by idodod**

### CODE REVIEW

**Review by mikejholly — APPROVED** [review]

**Comment by idodod** [comment]
@idelvall 
I still get this error though:
```
Execution failed for task ':publishPlugin'.
            +publish *failed* | > Failed to upload plugin: Upload failed: The vendor's trader/non-trader status has not been declared. Please specify it by visiting this link: https://plugins.jetbrains.com/author/me.
```
Is that something you can address?

**Comment by idelvall** [comment]
let me see, this is the first time i see this one

**Comment by idelvall** [comment]
@idodod it should be resolved, please try again

**Comment by idodod** [comment]
> @idodod it should be resolved, please try again

Thanks @idelvall do the changes in this PR look good to you? I just followed the example from earthly/lib

**Review by idelvall — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
