### PR TITLE
Add extra features to plugin

### PR DESCRIPTION
**Pull request by ingwarsw**
Basic features added:
- Fixed function names colors
- Some extra colors in highlighter
- Add commenter
- Added completion (works for targets and functions)
- Added go to definition/usage (works for targets and functions)
- Added find usages (works for targets and functions)
- Working refactoring (works for targets and functions)
- Added custom name validator to validate targets and function names properly

Extras:
- Added basic parsing tests
- Upgraded requirement to 2023.2.6 (maybe we can lower it to 2022.1, but upgrade was needed)
- Upgraded java to 17
- Added test pipeline for PRs

Needs first merge https://github.com/earthly/earthfile-grammar/pull/11

Things I was not able to do:
- Full parsing support NOT WORKING, maybe in the future will be usefull see (tried to migrate to antlr support for exactly same parser as Earthly is using internally see #35)

### CODE REVIEW

**Comment by idelvall** [comment]
Thanks for the effort Karol, it's looking promising. 
What do you mean by "Full parsing support NOT WORKING"?

**Comment by ingwarsw** [comment]
In IDE parser will not tell you that you have error at that line.. or your missing something somewhere.. according to parsing rules..

To test I just added [one rule](https://github.com/earthly/earthly-intellij-plugin/pull/34/files#diff-09b13c440acc0c3ee852fcc9da0a4bc36e30ba85e41d4ca93d9dacaadccb1b5dR41) that checks if `function` test with `:` (but thats the only rule, and to add all others manually i would spend ages), automatic attempt failed [here](https://github.com/earthly/earthly-intellij-plugin/pull/35).

Example parsing error looks like that
image

**Comment by idelvall** [comment]
I see. We need this working before merging. 
If you can do it that would be ideal, otherwise it might take some time for me to be able to focus on this

**Comment by ingwarsw** [comment]
@idelvall Moved all here.. its much much much simpler now..

**Review by alexcb — COMMENTED** [review]
This looks much more comprehensive; I'm just commenting to prevent receiving daily notification reminders -- leaving it up to Nacho to continue with the PR review (thanks!)

**Comment by ingwarsw** [comment]
@idelvall Is there anything I could help with?
Maybe we could just do quick meeting to talk about it and then would be easier to decide..

If your not planning releasing it maybe I can release it myself..

**Review by idelvall — APPROVED** [review]
LGTM.
Great work @ingwarsw!

**Pull request merged**
